### ISSUE TITLE
overflowerror by cvxopt

### ISSUE THREAD

**Issue by xubeisi** [rajanil/msCentipede#15]
msCentipede works fine for test data, but when I tried applied to other data with ATAC-seq model, learn model gives

/home/bxu2/opt/msCentipede/mscentipede.py:15: RuntimeWarning: overflow encountered in exp
  logistic = lambda x: 1./(1+np.exp(x))
/home/bxu2/opt/msCentipede/mscentipede.py:598: RuntimeWarning: overflow encountered in exp
  func = arg \* zeta.estim[:,1:] - nplog(1 + np.exp(arg))
Restart 1 ...
Traceback (most recent call last):
  File "/home/bxu2/opt/msCentipede/msCentipede_call.py", line 279, in <module>
    main()
  File "/home/bxu2/opt/msCentipede/msCentipede_call.py", line 272, in main
    learn_model(options)
  File "/home/bxu2/opt/msCentipede/msCentipede_call.py", line 47, in learn_model
    background_counts, options.model, options.restarts, options.mintol)
  File "/home/bxu2/opt/msCentipede/mscentipede.py", line 1133, in estimate_optimal_model
    alpha, beta, omega, pi_null, tau_null, model)
  File "/home/bxu2/opt/msCentipede/mscentipede.py", line 982, in square_EM
    EM(data, scores, zeta, pi, tau, alpha, beta, omega, pi_null, tau_null, model)
  File "/home/bxu2/opt/msCentipede/mscentipede.py", line 926, in EM
    beta.update(scores, zeta)
  File "/home/bxu2/opt/msCentipede/mscentipede.py", line 628, in update
    self.estim = optimizer(xo, function, gradient, hessian, scores=scores, zeta=zeta)
  File "/home/bxu2/opt/msCentipede/mscentipede.py", line 704, in optimizer
    solution = solvers.cp(F)
  File "build/bdist.linux-x86_64/egg/cvxopt/cvxprog.py", line 1969, in cp
  File "build/bdist.linux-x86_64/egg/cvxopt/cvxprog.py", line 715, in cpl
OverflowError: (34, 'Numerical result out of range')

I googled found this is something seems [related to the precision limitation](http://stackoverflow.com/questions/12666600/overflowerror-numerical-result-out-of-range-when-generating-fibonacci-numbers), but I am wondering is this something I can correct in msCentipede or I have to dig into cvxopt?

Thanks!

**Comment by davemcg** [comment]
I'm having the same issue. Is msCentipede not being updated anymore?
