### ISSUE TITLE
Cannot infer on ATAC-seq data

### ISSUE THREAD

**Issue by daquang** [rajanil/msCentipede#4]
I tried to infer on some ATAC-seq data, but I got the following error:

Traceback (most recent call last):
  File "call_binding.py", line 323, in <module>
    main()
  File "call_binding.py", line 319, in main
    infer_binding(options)
  File "call_binding.py", line 165, in infer_binding
    footprint_model, count_model, prior, options.model)
  File "mscentipede.pyx", line 1433, in mscentipede.infer_binding_posterior (mscentipede.c:26973)
    pi_null.value[j] = np.sum(np.sum(data_null.valueA[j],0),0) \
KeyError: 7

Here's the command I used:
python call_binding.py --protocol ATAC_seq --task infer test/Ctcf_chr10_motifs_atac.txt.gz data.bam

**Comment by rajanil** [comment]
Thanks for bringing up this issue! I've fixed the bug now. Could you try again and let me know if you still get this error and/or encounter any other issues?

thanks!

**Comment by daquang** [comment]
Works great!
